2021-07-27 10:50:15,309 ERROR: Exception on /user/amlich-hnd.js [GET] [in C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py: 1891]
Traceback (most recent call last):
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\son_n\.conda\envs\flask\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "d:\software_laptrinh\Python Learning\11. Github_repo\Flask\1_website_tu_vi\app\routes.py", line 115, in truy_xuat_gia_chu
    thong_tin_gia_chu = chuoi_HTML_gia_chu(username)
  File "d:\software_laptrinh\Python Learning\11. Github_repo\Flask\1_website_tu_vi\app\routes.py", line 270, in chuoi_HTML_gia_chu
    destination = UserDestination.query.filter_by(user_id=int(user.id)).first()
AttributeError: 'NoneType' object has no attribute 'id'
